# Generated by Django 4.2.6 on 2023-10-23 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ESTUDIANTES', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horarioinicio', models.CharField(max_length=150, verbose_name='Inicio')),
                ('horariofin', models.CharField(max_length=150, verbose_name='Fin')),
                ('cupo', models.IntegerField()),
                ('imagen', models.ImageField(default='users_pictures/default.png', upload_to='PortadasCursos')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'RegistroCursos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Añadir', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Registro de Docente',
                'verbose_name_plural': 'Registro de Docentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota Final')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Comentario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_y_Docentes.cursos', verbose_name='Curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTES.allusuarios', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'RegistroNotas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='inges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150, verbose_name='Nombre de usuario')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150)),
                ('cui', models.CharField(max_length=13, verbose_name='DPI')),
                ('imagen', models.ImageField(default='users_pictures/default.png', upload_to='PerfilesDocentes', verbose_name='Foto de Perfil')),
                ('login_attempts', models.IntegerField(default=0)),
                ('active_account', models.BooleanField(default=True)),
                ('account_locked', models.BooleanField(default=False, verbose_name='Bloquear usuario')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'RegistrosDocentes',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cursos',
            name='docentes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_y_Docentes.inges'),
        ),
    ]
