# Generated by Django 4.1.1 on 2023-10-26 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin_y_Docentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='estudiantes_inscritos',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudiantecurso',
            name='curso',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Estudiantes'}, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_asignados', to='Admin_y_Docentes.cursos', verbose_name='Curso'),
        ),
    ]
