# Generated by Django 4.1.1 on 2023-10-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inges',
            name='email',
            field=models.EmailField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
