# Generated by Django 4.2.6 on 2023-10-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inges',
            options={'ordering': ['cui'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.RemoveField(
            model_name='inges',
            name='id',
        ),
        migrations.AlterField(
            model_name='inges',
            name='email',
            field=models.EmailField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
