# Generated by Django 4.1.1 on 2023-10-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del curso'),
        ),
    ]
