# Generated by Django 4.1.1 on 2023-10-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIANTES', '0001_initial'),
        ('Admin_y_Docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_y_Docentes.cursos', verbose_name='Curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ESTUDIANTES.allusuarios', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asignaciones y Desasigaciones',
                'verbose_name_plural': 'Asignaciones y Desasigaciones',
                'db_table': 'Asigaciones_y_Desasignaciones',
                'ordering': ['id'],
            },
        ),
    ]
