# Generated by Django 4.1.1 on 2023-10-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0002_cursos_estudiantes_inscritos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantecurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_asignados', to='Admin_y_Docentes.cursos', verbose_name='Curso'),
        ),
    ]
