# Generated by Django 4.1.1 on 2023-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0002_estudiantecurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantecurso',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
