# Generated by Django 4.1.1 on 2023-10-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIANTES', '0001_initial'),
        ('Admin_y_Docentes', '0002_inges_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='estudiantes_inscritos',
            field=models.ManyToManyField(blank=True, related_name='cursos_inscritos', to='ESTUDIANTES.allusuarios'),
        ),
    ]
