# Generated by Django 4.1.1 on 2023-10-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIANTES', '0002_allusuarios_estudiantes_inscritos'),
        ('Admin_y_Docentes', '0003_estudiantecurso_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='estudiantes_inscritos',
            field=models.ManyToManyField(related_name='cursos_inscritos', to='ESTUDIANTES.allusuarios'),
        ),
    ]
