# Generated by Django 4.1.1 on 2023-10-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0004_alter_cursos_estudiantes_inscritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='estudiantes_inscritos',
        ),
        migrations.AlterField(
            model_name='estudiantecurso',
            name='asignado',
            field=models.BooleanField(default=False, verbose_name='PAGAR'),
        ),
    ]
