# Generated by Django 4.1.1 on 2023-10-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0005_remove_cursos_estudiantes_inscritos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantecurso',
            name='asignado',
            field=models.BooleanField(default=False, verbose_name='Asignado y Pagado'),
        ),
    ]
