# Generated by Django 4.1.1 on 2023-10-24 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ESTUDIANTES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusuarios',
            name='estudiantes_inscritos',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
