# Generated by Django 4.1.1 on 2023-10-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESTUDIANTES', '0002_allusuarios_estudiantes_inscritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusuarios',
            name='estudiantes_inscritos',
        ),
    ]
