# Generated by Django 4.2.6 on 2023-11-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
