# Generated by Django 4.1.1 on 2023-10-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0002_alter_inges_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='horario',
        ),
        migrations.AddField(
            model_name='cursos',
            name='horariofin',
            field=models.CharField(default=2, max_length=150, verbose_name='Fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='horarioinicio',
            field=models.CharField(default=2, max_length=150, verbose_name='Inicio'),
            preserve_default=False,
        ),
    ]
