# Generated by Django 4.1.1 on 2023-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0003_remove_cursos_horario_cursos_horariofin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
