# Generated by Django 4.1.1 on 2023-10-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0004_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inges',
            name='username',
            field=models.CharField(default='', max_length=150, verbose_name='Nombre de usuario'),
        ),
    ]
