# Generated by Django 4.1.1 on 2023-10-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0005_alter_inges_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Añadir', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='click',
        ),
    ]
