# Generated by Django 4.2.6 on 2023-10-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_y_Docentes', '0006_registros_delete_click'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inges',
            options={'ordering': ['id'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='registros',
            options={'ordering': ['id'], 'verbose_name': 'Registro de Docente', 'verbose_name_plural': 'Registro de Docentes'},
        ),
    ]
