# Generated by Django 4.1.1 on 2023-10-21 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allusuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Nombre', max_length=150)),
                ('last_name', models.CharField(default='Apellidos', max_length=150)),
                ('username', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=150)),
                ('email', models.EmailField(default='direccion@gmail.com', max_length=150)),
                ('cui', models.CharField(default='0', max_length=13)),
                ('profile_image', models.ImageField(default='users_pictures/default.png', upload_to='Perfiles')),
                ('login_attempts', models.IntegerField(default=0)),
                ('active_account', models.BooleanField(default=True)),
                ('account_locked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Estudiante',
                'verbose_name_plural': 'Registro de Estudiantes',
                'db_table': 'RegistrosEstudiantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horario', models.CharField(max_length=150)),
                ('cupo', models.IntegerField()),
                ('imagen', models.ImageField(default='users_pictures/default.png', upload_to='users_pictures')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'RegistroCursos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cursos')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.allusuarios')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'RegistroNotas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Docente',
                'verbose_name_plural': 'Registro de Docentes',
                'db_table': 'RegistrosDocentes',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cursos',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.docentes'),
        ),
    ]
