# Generated by Django 4.1.1 on 2023-10-19 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Apellido', models.CharField(max_length=150)),
                ('username', models.CharField(default='Docentes', max_length=150)),
                ('cui', models.CharField(max_length=13)),
                ('login_attempts', models.IntegerField(default=3)),
                ('active_account', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Registro de Docente',
                'verbose_name_plural': 'Registro de Docentes',
                'db_table': 'RegistrosDocentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horario', models.CharField(max_length=150)),
                ('cupo', models.IntegerField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.docentes')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'RegistroCursos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='allusuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Nombre', max_length=150)),
                ('last_name', models.CharField(default='Apellidos', max_length=150)),
                ('username', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=150)),
                ('email', models.EmailField(default='direccion@gmail.com', max_length=150)),
                ('cui', models.CharField(default='0', max_length=13)),
                ('profile_image', models.ImageField(default='users_pictures/default.png', upload_to='users_pictures')),
                ('login_attempts', models.IntegerField(default=0)),
                ('active_account', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Docente',
                'verbose_name_plural': 'Registro de Docentes',
                'db_table': 'RegistrosEstudiantes',
                'ordering': ['id'],
            },
        ),
    ]
