# Generated by Django 4.1.1 on 2023-10-21 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allusuarios',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allusuarios',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
