# Generated by Django 4.1.1 on 2023-10-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allusuarios',
            options={'ordering': ['id'], 'verbose_name': 'Registro de Estudiante', 'verbose_name_plural': 'Registro de Estudiantes'},
        ),
    ]
