# Generated by Django 4.1.1 on 2023-10-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_docentes_username_alter_docentes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='account_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
