# Generated by Django 4.1.1 on 2023-10-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_allusuarios_cui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusuarios',
            name='cui',
            field=models.BigIntegerField(unique=True),
        ),
    ]
