# Generated by Django 4.1.1 on 2023-10-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_docentes_account_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusuarios',
            name='profile_image',
            field=models.ImageField(default='users_pictures/default.png', upload_to='Perfiles'),
        ),
    ]
