# Generated by Django 4.1.1 on 2023-10-18 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_allusuarios_cui'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allusuarios',
            options={'ordering': ['id'], 'verbose_name': 'Registro de Docente', 'verbose_name_plural': 'Registro de Docentes'},
        ),
        migrations.AlterModelTable(
            name='allusuarios',
            table='RegistrosEstudiantes',
        ),
        migrations.CreateModel(
            name='docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='Nombres', max_length=150)),
                ('Apellido', models.CharField(default='Apellidos', max_length=150)),
                ('username', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=150)),
                ('email', models.EmailField(default='direccion@gmail.com', max_length=150)),
                ('cui', models.CharField(default='0', max_length=13)),
                ('profile_image', models.ImageField(default='users_pictures/default.png', upload_to='users_pictures')),
                ('login_attempts', models.IntegerField(default=0)),
                ('active_account', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Docente',
                'verbose_name_plural': 'Registro de Docentes',
                'db_table': 'RegistrosDocentes',
                'ordering': ['id'],
            },
        ),
    ]
