# Generated by Django 4.1.1 on 2023-10-18 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0005_alter_allusuarios_options_alter_allusuarios_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docentes',
            name='user',
        ),
        migrations.AddField(
            model_name='docentes',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='username',
            field=models.CharField(default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'), max_length=150),
        ),
    ]
