# Generated by Django 4.1.1 on 2023-10-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_docentes_user_docentes_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docentes',
            name='group',
        ),
        migrations.AlterField(
            model_name='docentes',
            name='username',
            field=models.CharField(default='Docentes', max_length=150),
        ),
    ]
