# Generated by Django 4.1.1 on 2023-10-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_docentes_group_alter_docentes_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docentes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='docentes',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='docentes',
            name='cui',
            field=models.CharField(max_length=13),
        ),
    ]
