# Generated by Django 4.1.1 on 2023-10-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_docentes_email_remove_docentes_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='Apellido',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='Nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='login_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
