# Generated by Django 4.1.1 on 2023-10-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customdocentes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDocentes',
        ),
    ]
