# Generated by Django 4.1.1 on 2023-10-19 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_customdocentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horario', models.CharField(max_length=150)),
                ('cupo', models.IntegerField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.docentes')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'RegistroCursos',
                'ordering': ['id'],
            },
        ),
    ]
