# Generated by Django 4.1.1 on 2023-10-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_cursos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='imagen',
            field=models.ImageField(null=True, upload_to='FD'),
        ),
    ]
